version: 2
jobs:
  build:
    # Variable expansion in working_directory not supported at this time
    # You will need to modify the code below to reflect your github account/repo setup
    working_directory: /go/src/github.com/rogerfdias/deployer
    docker:
      - image: circleci/golang:latest
    environment:
      GO15VENDOREXPERIMENT: 1
    branches:
      only:
        - master
    steps:
      - checkout
      - setup_remote_docker

      - run: echo 'export GOPATH_HEAD="$(echo ${GOPATH}|cut -d ':' -f 1)"' >> $BASH_ENV
      - run: echo 'export GOPATH_BASE="${GOPATH_HEAD}/src/github.com/${CIRCLE_PROJECT_USERNAME}"' >> $BASH_ENV
      - run: echo 'export DOCKER_REPO="$(if [ ${CIRCLE_PROJECT_USERNAME} == 'rogerfdias' ]; then echo rogerfdias; else echo $DOCKER_USER; fi)"' >> $BASH_ENV
      - run: mkdir -p "${GOPATH_BASE}"
      - run: mkdir -p "${GOPATH_HEAD}/bin"
      - run: go get github.com/govend/govend
      - run: sudo apt-get -y install jq postgresql-client awscli

      - run:
          name: Build application container
          command: |
            go install --ldflags '-extldflags "-static"' github.com/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME};
            [ ! -e bin ] && mkdir bin;
            cp "${GOPATH_HEAD}/bin/${CIRCLE_PROJECT_REPONAME}" bin/deployer;
            chmod +x deploymentTests/*
            docker build -t ${DOCKER_REPO}/${CIRCLE_PROJECT_REPONAME} .;

      - deploy:
          # Push application container to dockerhub
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
                echo ${DOCKER_PASS} | docker login -u ${DOCKER_USER} --password-stdin;
                echo ${DOCKER_USER}/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_TAG};
                docker images --no-trunc | awk '/^app/ {print $3}' | sudo tee $CIRCLE_ARTIFACTS/docker-image-shasum256.txt;
                docker push ${DOCKER_REPO}/${CIRCLE_PROJECT_REPONAME};
            fi
            
